In [3]:
import json
import torch
import os
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F

In [12]:
x = torch.arange(10).reshape((2, 5))
print(x)
# x = torch.tensor([[1,2,3,0],[1,2,1,1]])
print(x.shape)
y = F.one_hot(x, 10)
print(y.shape)
print(y)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.Size([2, 5])
torch.Size([2, 5, 10])
tensor([[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]])


In [32]:
f = open('./Dataset/metadata.json', 'r')
t = json.load(f)
print(t['n_mels'])

print(len(t['speakers']['id03074'][0]['feature_path']))
path = t['speakers']['id03074'][0]['feature_path']
print(path)
tensor = torch.load(os.path.join('Dataset', path))
print(tensor.shape)
transformer = nn.TransformerEncoderLayer(40, 8)
x = torch.rand([2,123,40])
y = transformer(x)
print(y.shape)
x2 = torch.rand([3,123,40])
y = transformer(x, x2)
print(y.shape)

40
40
uttr-18e375195dc146fd8d14b8a322c29b90.pt
torch.Size([435, 40])
torch.Size([2, 123, 40])


RuntimeError: The shape of the 3D attn_mask is torch.Size([3, 123, 40]), but should be (984, 2, 2).

In [ ]:
metadata = json.load(open(os.path.join('Dataset', 'metadata.json', 'r')))
class MyDataset(Dataset):
    def __init__(self, mode='train'):
        super().__init__()
        self.mode = mode
        self.y = None
        if self.mode == 'train':


In [41]:
l = torch.tensor([1,2,3,4])
l[[1,2]]
# l = [1,2,3]
# l[(1,2)]

tensor([2, 3])